# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "paknife-centos-6.6"
  config.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.6_chef-provisionerless.box"

  config.vm.define "s1" do |s1|
    s1.vm.network "private_network", ip: "192.168.33.55"
  end

  config.vm.define "s2" do |s2|
    s2.vm.network "private_network", ip: "192.168.33.56"
  end
end
